### ISSUE TITLE
Make hChaCha20 public

### ISSUE THREAD

**Issue by jedisct1** [aead/chacha20#15]
Hi Andreas,

And thanks for this great package.

Just a tiny request: would it be possible make `hChaCha20()` public?

This would be useful to reimplement libsodium's `crypto_box_xchacha20poly1305` in Go.

Thanks!

**Comment by aead** [comment]
Sry for the long delay - fixed 😃

**Comment by jedisct1** [comment]
No problem. Thanks a lot!
