### ISSUE TITLE
xorKeyStreamAVX2 mishandles counter overflow

### ISSUE THREAD

**Issue by lukechampine** [aead/chacha20#16]
Repro:
```go
func TestOverflow(t *testing.T) {
	nonce := make([]byte, 8)
	key := make([]byte, 32)
	stream, _ := NewCipher(nonce, key, 20)

	// Set the counter to uint64-max and encrypt a two-block plaintext. This
	// should cause the counter to overflow to 1.
	plaintext := []byte("This is an example plaintext " +
		" that should require two blocks to encrypt")
	ciphertext := make([]byte, len(plaintext))
	stream.SetCounter(^uint64(0))
	stream.XORKeyStream(ciphertext, plaintext)

	// Reset the counter to 0 and attempt the decrypt the second block of the
	// ciphertext.
	stream.SetCounter(0)
	plaintextSuffix := make([]byte, len(plaintext[64:]))
	stream.XORKeyStream(plaintextSuffix, ciphertext[64:])
	if !bytes.Equal(plaintextSuffix, plaintext[64:]) {
		t.Fatal("failed to decrypt second block")
	}
}
```

When `xorKeyStream` is `xorKeyStreamAVX2`, this test fails. For any other value of `xorKeyStream`, it succeeds.

One other useful piece of info: If I split the initial xor into two calls, i.e.:
```go
stream.SetCounter(^uint64(0))
stream.XORKeyStream(ciphertext[:64], plaintext[:64])
stream.XORKeyStream(ciphertext[64:], plaintext[64:])
```
the decryption succeeds.

**Comment by aead** [comment]
Thanks for the report, can confirm that there is something wrong in the AVX2 code. Will investigate...

**Comment by jedisct1** [comment]
The code increments `Y3`, which includes the counter but also a part of the nonce. So, on overflow, we also increment the nonce.

Neither the original paper nor the RFCs seems to document what the behavior should be when the internal counter overflows, as this should never happen when the cipher is used as expected.
